### PR TITLE
New features collection

### PR DESCRIPTION
**Pull request by opatut**
This branch contains a lot of new features that I've been working on but never finished, for some reason or another. I wanted to get this all out and cleaned up so I can start working on other exciting stuff without all that baggage ;)

Features:

* Administrative areas (replaces #227, #288)
* Some API-internal fixes and improvements
* Device identifiers

### CODE REVIEW

**Comment by gluap** [comment]
trying to upgrade the db alembic tells me that there are multiple had revisions - and it's right:

both "add_user_display_name" and "create-Table_road_usage" are the head. (they point to the same prior revision as base).

**Comment by gluap** [comment]
@opatut yes.
- I love the new tracks list, much cleaner and concise than the old one.
  - I notice that this fixes #330 :heart:, hadn't remembered this earlier because I was focusing on the device id feature.
- This update will require a reimport of the geodata.
- This update will require recomputing all tracks to extract the device IDs.
- I don't know why but the administrative areas perform better than on my retrofitted version of the branch.
- I removed the sonarcloud complaints by fixing them / nodding about the log injection alert.

**Comment by gluap** [comment]
I could deploy this on the ADFC-Hessen portal, @Nugman asked me to update the map there anyhow, might as well do the upgrade beforehand.

**Review by gluap — APPROVED** [review]
I tested this (by clicking through my test portal deployment). As mentioned there are too many changes to do a code based review.

I strongly suggest to add the required upgrade steps (maps reimport, recompute tracks unless I missed something) to the readme before announcing this as an upgrade.

I will report back once a live test is deployed.

**Comment by gluap** [comment]
@opatut I have it running on https://obs.adfc-hessen.de now. Observations:

- The region map is VERY slow to render. About 40 seconds per tile. Users scrolling wildly on the map will spawn a whole bunch of postgress processes. Just zooming there quickly brings the load on the two-core machine to above 20. And we're doing basically the same expensive operation (checking if an event is within polygon bounds) for every map tile again and again (even though the polygons are so large that they are the same for neighboburing map tiles). [Look at this area](https://obs.adfc-hessen.de/map#9.71/50.070442463022204/8.402336996088774) for instance.
  -  Maybe we should go the same way we went for the roads and compute an event region on track evaluation. That way the expensive operation would only take place once, on track import.

**Comment by gluap** [comment]
I agree it is strange that it is so much slower - For my Desktop it is more performant, too. But on the other hand my desktop has 16 gig of ram with only the hessen map active (while the obs.adfc-hessen.de has only two and the germany map imported).

**Comment by gluap** [comment]
Intermediate report: Slowness seems to have gone away now that I reduced the map import to only Hesse - Maybe having all of Germany imported increases the number of Geopolygons we check by a large number (there's like 300 Kreise and Kreisfreie Städte or so), and thus made it slow? Previously we were using the whole Germany map.

**Comment by gluap** [comment]
I found one way to speed up the regions layer: Restricting the query to only admin_level 6 makes it much smoother.

**Comment by boldt** [comment]
My last commit fixes the Menu on mobile:

### Before

Vorher


### After

Nachher

**Comment by gluap** [comment]
I just noticed that we have lost the ".env" file from the deployment/examples in this branch.

**Pull request merged**
