### PR TITLE
correct container name is "api"

### PR DESCRIPTION
**Pull request by gluap**
This command needs to be run in the ``api`` (or ``worker``) container. There is no ``portal`` container.

### CODE REVIEW

**Comment by gluap** [comment]
@opatut mention because It's an easy fix and you've likely not gotten a notification from the PR#

**Comment by opatut** [comment]
No there is one in the deployment docker compose. The name is different because the image is different, and it contains API and frontend, so I called it portal. These commands are therefore correct.

**Comment by opatut** [comment]
See https://github.com/openbikesensor/portal/blob/main/deployment/examples/docker-compose.yaml#L20

**Comment by gluap** [comment]
Ah, I see, I'll check whether that needs clarification or whether I just overrread something. Pardon me for not noticing.

**Pull request closed without merging**
